# Generated by Django 6.0.1 on 2026-01-29 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField()),
                ('osm_type', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Resolved'), (3, 'Clean'), (4, 'False Alarm'), (5, 'Cleared'), (6, 'Urgent')])),
                ('first_reported', models.DateField()),
                ('last_seen', models.DateField()),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('action', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='trash_imgs/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('camera_model', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__gte', 0), ('severity__lte', 10)), name='severity_between_0_and_10')],
            },
        ),
    ]
