# Generated by Django 6.0.1 on 2026-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashticket',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
